'use strict';
// Kiswahili content uses the same hero, cards and section classes as the
// repository's original homepage — it is not a separate visual redesign.
const X = require('../layout');
const { esc } = require('../lib');
const { icon, pic, btn, sectionHead } = X;
module.exports = { render(ctx, heroSection) {
  const s = ctx.db.settings, academic = ctx.db.academics;
  const news = ctx.db.news.filter(item => item.language === 'sw').slice(0, 3);
  const slides = [
    { kicker: 'Karibu Alpha', title: 'Karibu Shule ya Awali na Msingi Alpha Adventist', text: 'Taasisi ya elimu ya Waadventista Wasabato ndani ya Western Tanzania Conference – Kigoma, inayokuza maarifa, nidhamu, ubunifu, uwajibikaji na maisha ya kiroho.', strap: 'Elimu • Imani • Teknolojia • Vipaji • Tabia • Mustakabali', cta: { label: 'Omba Nafasi ya Masomo', href: '/sw/admissions#apply' }, cta2: { label: 'Panga Ziara ya Shule', href: '/sw/admissions#visit' } },
    { kicker: 'Taaluma', title: 'Msingi Imara wa Taaluma kwa Kila Mwanafunzi', text: 'Mafunzo yanayokuza maarifa, kujiamini, nidhamu na shauku ya kujifunza.', cta: { label: 'Fahamu Masomo Yetu', href: '/academics' } },
    { kicker: 'Teknolojia', title: 'Kuwaandaa Watoto kwa Mustakabali wa Kidijitali', text: 'Mafunzo ya kompyuta ya vitendo, ubunifu na matumizi salama ya teknolojia.', cta: { label: 'Fahamu Mafunzo ya Kompyuta', href: '/computer-learning' } },
    { kicker: 'Imani, Vipaji na Maisha ya Shule', title: 'Kumkuza Mtoto kwa Ujumla', text: 'Imani, tabia, vipaji, ubunifu, ushirikiano na uongozi ni sehemu ya maisha ya Alpha.', cta: { label: 'Gundua Maisha ya Shuleni', href: '/school-life' } }
  ];
  const pillars = [
    ['book', 'Elimu', 'Msingi imara wa maarifa na ujuzi wa kujifunza maisha yote.', '/academics'],
    ['flame', 'Imani', 'Maadili ya Kikristo, uadilifu, heshima, uwajibikaji na huduma.', '/faith'],
    ['chip', 'Teknolojia', 'Ujuzi wa vitendo na matumizi salama ya teknolojia.', '/computer-learning'],
    ['star', 'Vipaji', 'Nafasi za kugundua na kukuza uwezo wa kila mtoto.', '/talents'],
    ['shield', 'Tabia', 'Nidhamu, uwajibikaji na mahusiano yenye heshima.', '/faith#character'],
    ['rocket', 'Mustakabali', 'Maarifa, tabia njema na kujiamini kwa hatua zinazofuata maishani.', '/computer-learning#future']
  ];
  const wa = 'https://wa.me/' + s.whatsapp.href;
  return { body: `${heroSection({ ...ctx, homeSlides: slides })}
<section class="trust" aria-label="Kwa nini Alpha"><div class="container"><div class="trust__grid">${pillars.map(([ic, name, description, href]) => `<a class="trust__card rv" href="${href}"><div class="trust__ico">${icon(ic)}</div><div><h3>${name}</h3><p>${description}</p></div></a>`).join('')}</div></div></section>
<section class="sec" id="who-we-are"><div class="container split"><div class="media-stack"><div class="media-stack__main">${pic('', '', { ratio: '4/3' })}</div></div><div>${sectionHead('Sisi ni Nani', 'Jamii ya Kujifunza Inayojengwa kwa Hekima Katika Ukweli', 'Alpha Adventist ni shule ya Waadventista Wasabato iliyopo Msimba, Kigoma. Tunazingatia ukuaji wa mtoto kiakili, kiroho, kimwili na kijamii.')}<ul class="checklist"><li>${icon('check')}<span>Msingi wa taaluma kuanzia KG I hadi Standard VII.</span></li><li>${icon('check')}<span>Imani na tabia njema kupitia ibada, kujifunza Biblia na huduma.</span></li><li>${icon('check')}<span>Ubunifu, vipaji na ujuzi wa kidijitali unaolingana na umri.</span></li></ul>${btn('/about', 'Fahamu Zaidi Kuhusu Alpha', 'primary', 'arrow')}</div></div></section>
<section class="sec sec--sand" id="pillars"><div class="container">${sectionHead('Nguzo Sita za Alpha', 'Kumjenga Mtoto kwa Ujumla', 'Elimu yetu inakuza maarifa, imani, tabia na uwezo wa kila mwanafunzi.', { align: 'center' })}<div class="pillars">${pillars.map(([ic, name, description, href], i) => `<article class="pillar rv"><span class="pillar__num" aria-hidden="true">0${i + 1}</span><div class="pillar__ico">${icon(ic)}</div><h3>${name}</h3><p>${description}</p><a class="link-more" href="${href}">Fahamu zaidi ${icon('arrow')}</a></article>`).join('')}</div></div></section>
<section class="sec" id="academics"><div class="container">${sectionHead('Madarasa Yetu', 'Kuanzia Hatua za Kwanza Hadi Darasa la Saba', 'Mafunzo ya awali na msingi kwa wanafunzi wa kutwa na bweni, kwa uongozi wa walimu.')}<div class="levels"><div class="level-box"><h3>${icon('sun')} Elimu ya Awali</h3><p>Lugha, hesabu, michezo na ugunduzi katika mazingira yenye upendo na imani.</p><ul class="level-chips">${academic.prePrimary.map(name => `<li>${esc(name)}</li>`).join('')}</ul></div><div class="level-box"><h3>${icon('book')} Elimu ya Msingi</h3><p>Kujenga maarifa, kujiamini na tabia njema kupitia mtaala wa elimu ya msingi.</p><ul class="level-chips">${academic.primary.map(name => `<li>${esc(name)}</li>`).join('')}</ul></div></div><div class="grid grid--2" style="margin-top:22px"><article class="card"><div class="card__ico">${icon('home')}</div><h3>Kutwa</h3><p>Masomo, ibada na shughuli za kila siku katika mazingira ya shule.</p></article><article class="card"><div class="card__ico">${icon('bed')}</div><h3>Bweni</h3><p>Wasiliana na ofisi kuthibitisha nafasi za bweni na mahitaji ya darasa husika.</p></article></div></div></section>
<section class="sec techband" id="technology"><div class="container">${sectionHead('Kompyuta na Ujuzi wa Kidijitali', 'Kuwaandaa Wanafunzi kwa Mustakabali wa Kidijitali', 'Mafunzo ya vitendo, ubunifu na matumizi yenye kuwajibika ya teknolojia.')}<div class="techgrid"><article class="techcard"><h3>${icon('laptop')} Mafunzo kwa Wanafunzi</h3><p>Matumizi ya kompyuta, kibodi na kipanya, uandishi na usalama mtandaoni kulingana na umri.</p></article><article class="techcard"><h3>${icon('users')} Ujuzi kwa Walimu na Wafanyakazi</h3><p>Kuendeleza ujuzi wa kidijitali kwa ufundishaji, mawasiliano na utunzaji salama wa taarifa.</p></article><article class="techcard"><h3>${icon('lock')} Portal ya Wafanyakazi</h3><p>Huduma salama kwa watumishi walioidhinishwa: likizo, nyaraka, taarifa na maombi.</p>${btn('/portal','Ingia Portal','gold')}</article></div><p style="margin-top:24px">${btn('/computer-learning', 'Fahamu Mafunzo ya Kompyuta', 'light', 'arrow')}</p></div></section>
<section class="sec" id="school-life"><div class="container">${sectionHead('Maisha ya Alpha', 'Kujifunza, Imani, Urafiki na Ugunduzi', 'Ibada, muziki, huduma, miradi na teknolojia ni sehemu ya maisha ya shule.')}<div class="tiles">${[['music','Muziki na Kwaya'],['flame','Ibada na Imani'],['flask','Miradi ya Taaluma'],['chip','Ujuzi wa TEHAMA'],['badge','Mafanikio'],['heart','Huduma kwa Jamii']].map(([ic, title]) => `<div class="tile">${icon(ic)}<strong>${title}</strong></div>`).join('')}</div></div></section>
<section class="sec sec--sand" id="admissions-cta"><div class="container"><div class="ctaband"><span class="kicker">Uandikishaji</span><h2>Anza Safari ya Mtoto Wako Alpha</h2><p>Ofisi itakueleza ada za sasa, mahitaji na nafasi zilizopo kabla ya kufanya uamuzi.</p><ol class="steps"><li>Ifahamu Alpha</li><li>Panga Ziara</li><li>Tuma Ombi</li><li>Tathmini Inapohitajika</li><li>Uthibitisho wa Nafasi</li></ol><div class="home-actions">${btn('/sw/admissions#apply','Omba Nafasi','gold')}${btn('/sw/admissions#visit','Panga Ziara','outline-light')}</div></div></div></section>
${news.length ? `<section class="sec" id="news"><div class="container">${sectionHead('Habari na Matukio', 'Yanayojiri Alpha')}<div class="grid grid--3">${news.map(item => `<article class="news-card"><div class="news-card__in"><div class="news-meta"><span class="news-cat">${esc(item.category)}</span></div><h3><a href="/news/${esc(item.slug)}">${esc(item.title)}</a></h3><p>${esc(item.excerpt)}</p></div></article>`).join('')}</div></div></section>` : ''}
<section class="sec" id="parents"><div class="container">${sectionHead('Kwa Wazazi', 'Familia na Shule Pamoja')}<div class="parent-grid"><article class="card"><div class="card__ico">${icon('download')}</div><h3>Nyaraka za Shule</h3><p>Nyaraka zilizoidhinishwa kwa matumizi ya umma.</p>${btn('/downloads','Fungua Nyaraka','ghost')}</article><article class="card"><div class="card__ico">${icon('users')}</div><h3>Mawasiliano na Ofisi</h3><p>Uliza kuhusu ada, kujiunga, kutwa na bweni.</p>${btn('/sw/contact','Wasiliana Nasi','ghost')}</article></div></div></section>
<section class="sec kids" id="kids"><div class="container">${sectionHead('Alpha Kids Zone', 'Jifunze • Gundua • Fanya Mazoezi • Buni', 'Michezo ya kujifunza na usalama mtandaoni, bila matangazo au mazungumzo na wageni.', { align: 'center' })}<div class="kid-grid">${[['keyboard','Kuandika','/students#typing'],['sparkle','Hesabu','/students#maths'],['laptop','Kompyuta','/students#computer'],['shield','Usalama Mtandaoni','/students#safety']].map(([ic,title,href],i) => `<a class="kid-card" href="${href}"><span class="kid-card__ico kc-${i+1}">${icon(ic)}</span><strong>${title}</strong></a>`).join('')}</div></div></section>
<section class="sec sec--sand" id="contact"><div class="container">${sectionHead('Wasiliana', 'Tupo Kukusikiliza', 'Tunapatikana eneo la Msimba, Kigoma. Wasiliana nasi kuhusu ziara, uandikishaji au maisha ya shule.', { align: 'center' })}<div class="contact-grid"><a class="contact-card" href="tel:${esc(s.phones[0].href)}">${icon('phone')}<strong>Ofisi ya Shule</strong><span>${esc(s.phones[0].number)}</span></a><a class="contact-card" href="${esc(wa)}" target="_blank" rel="noopener noreferrer">${icon('whatsapp')}<strong>WhatsApp</strong><span>${esc(s.whatsapp.number)}</span></a><a class="contact-card" href="mailto:${esc(s.email)}">${icon('mail')}<strong>Barua Pepe</strong><span>${esc(s.email)}</span></a><a class="contact-card" href="/sw/contact">${icon('pin')}<strong>Mahali Tulipo</strong><span>${esc(s.locationText)}</span></a></div><p class="text-center" style="margin-top:24px">${btn('/sw/contact','Tuma Ujumbe','primary','send')}</p></div></section>`, meta: { title: 'Shule ya Awali na Msingi Alpha Adventist — Kigoma, Tanzania', desc: 'Elimu ya awali na msingi kwa ukuaji wa mtoto kwa ujumla. KG I hadi Standard VII, kutwa na bweni, Kigoma.', jsonld: X.schoolJsonLd(ctx) } };
} };
