'use strict';
const X = require('../layout');
const { esc } = require('../lib');
const { phero } = require('./about');
const { icon, sectionHead, btn } = X;
const consent = '<div class="field"><label class="adsp-consent"><input type="checkbox" name="privacy_consent" value="yes" required><span>Nimesoma <a href="/privacy">taarifa ya faragha (Kiingereza)</a> na nakubali shule kutumia taarifa hizi kujibu ombi langu. Ridhaa hii si ruhusa ya kuchapisha picha za mtoto.</span></label></div>';
const finish = label => `<input type="hidden" name="language" value="sw"><div class="hp-field" aria-hidden="true"><label>Acha sehemu hii wazi</label><input name="website_url" tabindex="-1" autocomplete="off"></div>${consent}<div class="form__status" role="status"></div><button class="btn btn--primary btn--block" type="submit">${icon('send')} ${label}</button>`;
function namePhone(prefix, nameLabel = 'Jina la mzazi au mlezi') {
  return `<div class="form__row"><div class="field"><label for="${prefix}-name">${nameLabel} *</label><input id="${prefix}-name" name="name" autocomplete="name" required maxlength="160"></div><div class="field"><label for="${prefix}-phone">Simu / WhatsApp *</label><input id="${prefix}-phone" name="phone" type="tel" autocomplete="tel" required maxlength="24"></div></div>`;
}
function admissions(ctx) {
  const levels = [...ctx.db.academics.prePrimary, ...ctx.db.academics.primary];
  return {
    body: `${phero(ctx, 'Uandikishaji', 'Safari ya mtoto wako inaanza hapa.', 'Elimu ya awali na msingi, kuanzia KG I hadi Standard VII. Wasiliana nasi kuhusu nafasi za kutwa na bweni.', 'campus')}
<section class="sec"><div class="container">${sectionHead('HATUA ZA KUJIUNGA', 'Hatua rahisi kwa familia yako.')}<ol class="adsp-steps"><li><strong>Ifahamu Alpha</strong><br>Soma kuhusu shule au wasiliana na ofisi.</li><li><strong>Tembelea shule</strong><br>Kutana na walimu na ujionee mazingira.</li><li><strong>Tuma ombi</strong><br>Jaza taarifa chache hapa chini.</li><li><strong>Tathmini inapohitajika</strong><br>Ofisi itaeleza hatua zinazohusika.</li><li><strong>Uthibitisho wa nafasi</strong><br>Pokea maelekezo rasmi ya kujiunga.</li></ol><div class="note-strip">${icon('clipboard')}<span>Ofisi itakupatia ada za sasa, mahitaji, sare na nafasi zilizopo kwa darasa husika. Kutuma ombi hili hakumaanishi kuwa nafasi imethibitishwa.</span></div></div></section>
<section class="sec sec--sand" id="apply"><div class="container split"><div>${sectionHead('OMBA NAFASI', 'Tuanze mazungumzo.','Jaza taarifa za msingi za mtoto na mlezi. Taarifa hizi huonekana kwa maafisa walioidhinishwa tu. Utapewa namba ya kumbukumbu.')}<ul class="checklist"><li>${icon('check')}<span>Awali: KG I na KG II</span></li><li>${icon('check')}<span>Msingi: Standard I hadi Standard VII</span></li><li>${icon('check')}<span>Kutwa na bweni, kulingana na nafasi zinazothibitishwa na ofisi.</span></li></ul><p>Usitume cheti cha kuzaliwa, taarifa za afya au nyaraka nyeti kupitia fomu hii. Ofisi itaeleza njia salama ikihitaji nyaraka.</p></div><form class="card form" data-endpoint="/api/apply"><h2>Ombi la kujiunga</h2><div class="form__row"><div class="field"><label for="sw-child">Jina kamili la mtoto *</label><input id="sw-child" name="child_name" required maxlength="160"></div><div class="field"><label for="sw-guardian">Jina la mzazi au mlezi *</label><input id="sw-guardian" name="guardian_name" autocomplete="name" required maxlength="160"></div></div><div class="form__row"><div class="field"><label for="sw-phone">Simu / WhatsApp *</label><input id="sw-phone" name="phone" type="tel" autocomplete="tel" required></div><div class="field"><label for="sw-email">Barua pepe (si lazima)</label><input id="sw-email" name="email" type="email" autocomplete="email"></div></div><div class="form__row"><div class="field"><label for="sw-level">Darasa *</label><select id="sw-level" name="level" required><option value="">Chagua darasa…</option>${levels.map(level => `<option value="${esc(level)}">${esc(level)}</option>`).join('')}</select></div><div class="field"><label for="sw-arrangement">Mpangilio *</label><select id="sw-arrangement" name="arrangement" required><option value="">Chagua…</option><option value="Day">Kutwa</option><option value="Boarding">Bweni</option></select></div></div><div class="field"><label for="sw-message">Swali au ujumbe (si lazima)</label><textarea id="sw-message" name="message" maxlength="2000"></textarea></div><p class="form__note">Kwa kutuma fomu, unathibitisha kuwa wewe ni mzazi au mlezi mwenye mamlaka ya kuwasilisha ombi hili.</p>${finish('Tuma ombi la kujiunga')}</form></div></section>
<section class="sec" id="visit"><div class="container split"><div>${sectionHead('TEMBELEA SHULE', 'Karibu Alpha.','Ziara ni nafasi ya kuuliza maswali, kukutana na timu na kupata maelekezo ya kujiunga. Ofisi itathibitisha siku na muda unaofaa.')}<p>${btn('/sw/contact', 'Wasiliana nasi', 'ghost', 'arrow')}</p></div><form class="card form" data-endpoint="/api/visit"><h2>Panga ziara</h2>${namePhone('sw-visit')}<div class="field"><label for="sw-day">Siku au muda unaopendelea</label><input id="sw-day" name="preferred_day" maxlength="160"></div><div class="field"><label for="sw-questions">Maswali kwa ofisi</label><textarea id="sw-questions" name="message" maxlength="2000"></textarea></div>${finish('Omba ziara ya shule')}</form></div></section>`,
    meta: { title: 'Uandikishaji — Shule ya Awali na Msingi Alpha Adventist, Kigoma', desc: 'Omba nafasi katika Shule ya Alpha Adventist, Kigoma. Elimu ya awali na msingi, kutwa na bweni. Panga ziara na upate taarifa za ada na mahitaji.' }
  };
}
function contact(ctx) {
  const s = ctx.db.settings;
  return {
    body: `${phero(ctx, 'Wasiliana', 'Tupo kukusikiliza.', 'Uliza kuhusu masomo, kujiunga au ziara ya shule. Tunapatikana eneo la Msimba, Kigoma.', 'campus')}
<section class="sec"><div class="container"><div class="contact-grid"><a class="contact-card" href="tel:${esc(s.phones[0].href)}">${icon('phone')}<strong>Ofisi ya shule</strong><span>${esc(s.phones[0].number)}</span></a><a class="contact-card" href="tel:${esc(s.phones[1].href)}">${icon('phone')}<strong>Ofisi ya mkuu wa shule</strong><span>${esc(s.phones[1].number)}</span></a><a class="contact-card" href="https://wa.me/${esc(s.whatsapp.href)}" target="_blank" rel="noopener noreferrer">${icon('whatsapp')}<strong>WhatsApp</strong><span>${esc(s.whatsapp.number)}</span></a><a class="contact-card" href="mailto:${esc(s.email)}">${icon('mail')}<strong>Barua pepe</strong><span>${esc(s.email)}</span></a></div><div class="split" style="margin-top:40px"><div>${sectionHead('ANWANI YETU', 'Karibu Msimba, Kigoma.')}<p>Alpha Adventist Pre &amp; Primary School<br>${esc(s.address.box)}, Kigoma, Tanzania</p><p>Ofisi hujibu wakati wa kazi katika siku za shule. Piga simu kuthibitisha muda wa ziara na kupata maelekezo sahihi ya kufika shuleni.</p><p>Kituo cha mitihani: <strong>${esc(s.centreCode)}</strong></p><p><a href="/safeguarding">Toa taarifa ya wasiwasi kuhusu usalama wa mtoto (Kiingereza)</a></p></div><form class="card form" data-endpoint="/api/contact"><h2>Tuma ujumbe</h2>${namePhone('sw-contact', 'Jina lako')}<div class="field"><label for="sw-contact-email">Barua pepe (si lazima)</label><input id="sw-contact-email" name="email" type="email" autocomplete="email"></div><div class="field"><label for="sw-contact-message">Ujumbe wako *</label><textarea id="sw-contact-message" name="message" required maxlength="2000"></textarea></div>${finish('Tuma ujumbe')}</form></div></div></section>`,
    meta: { title: 'Wasiliana — Shule ya Alpha Adventist, Msimba Kigoma', desc: 'Wasiliana na Shule ya Awali na Msingi Alpha Adventist, Msimba Kigoma. Piga simu +255 613 807 200, tuma ujumbe au panga ziara.', jsonld: X.schoolJsonLd(ctx) }
  };
}
module.exports = { admissions, contact };
